version: "3.8"

services:
  app:
    build: .
    container_name: meu_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: npm start
